# Generated by Django 5.2.1 on 2025-05-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The display name for this product. Keep it concise and descriptive.', max_length=200, verbose_name='Product Name')),
                ('sku', models.CharField(help_text='Unique identifier for inventory tracking. Auto-generated if left blank.', max_length=50, unique=True, verbose_name='SKU (Stock Keeping Unit)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Retail price in US dollars. Do not include currency symbol.', max_digits=10, verbose_name='Price (USD)')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Product weight in pounds. Used for shipping calculations.', max_digits=8, verbose_name='Weight (lbs)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this product from the storefront without deleting it.', verbose_name='Active Product')),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (160 characters max). Leave blank for auto-generation.', max_length=160, verbose_name='SEO Meta Description')),
                ('featured_until', models.DateTimeField(blank=True, help_text='Product will appear in featured section until this date. Leave blank to feature indefinitely.', null=True, verbose_name='Featured Until')),
            ],
        ),
    ]
