# Generated by Django 5.2.1 on 2025-05-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Retail price in Indian Currency. Do not include currency symbol.', max_digits=10, verbose_name='Price (Rupees)'),
        ),
    ]
